### ISSUE TITLE
希望多加功能

### ISSUE THREAD

**Issue by A125963** [city41/neospriteviewer#23] opened 2024-07-06 21:21 UTC
作者你好，希望能改成像C工具一样，能保存spr，能分割spr，能用调色版与导入导出图片。
![Screenshot_2024-07-07-05-10-38-832_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/22730f96-6e7b-4a67-832f-b5787f568c95)
![Screenshot_2024-07-07-05-10-48-250_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/6b5f0243-cca4-4f92-84bf-5f39f7822025)
![Screenshot_2024-07-07-05-10-50-704_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/beec3c3e-5467-4f8d-ad46-e990e038d8cb)
![Screenshot_2024-07-07-05-11-11-831_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/36ce01ba-f39b-48b7-b6d6-49f40e06018c)
![Screenshot_2024-07-07-05-11-13-764_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/babe03d7-6a83-431a-b025-36c524e27df4)
![Screenshot_2024-07-07-05-11-19-588_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/bc930895-26ee-478d-a798-473438f7da5e)
![Screenshot_2024-07-07-05-11-21-460_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/45187022-4e88-47eb-9fe3-b5d6ea825a29)

**Comment by city41** [comment] 2024-07-11 12:58
This is a duplicate of #22

**Closed as completed by city41** 2024-07-11 12:58 UTC
