### ISSUE TITLE
作者你好，能写得像C工具一样吗？

### ISSUE THREAD

**Issue by A125963** [city41/neospriteviewer#24] opened 2024-07-06 23:32 UTC
写得像C工具一样能合成SPR，能把SPR分成两个C，能用调色板，能导入导出图片。谢谢了，作者，相信你。
![Screenshot_2024-07-07-05-28-15-765_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/244ca43b-4d65-473e-ad1c-c2c0c39d915d)
![Screenshot_2024-07-07-05-28-44-883_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/ab9d3d9e-0a40-480b-8fd9-3cd769b573a9)
![Screenshot_2024-07-07-05-37-32-361_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/41975532-cc30-4472-a2b4-f488641e8da9)
![Screenshot_2024-07-07-07-24-55-546_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/762df609-45bd-4565-b16d-37e4cbab9cbd)
![Screenshot_2024-07-07-07-24-58-456_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/0bb73569-960c-4b53-9a55-d142a9f9a5e6)
![Screenshot_2024-07-07-07-25-02-554_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/ac08f544-db83-456f-840a-bd86af89436a)
![Screenshot_2024-07-07-07-25-09-785_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/1a771311-951f-4c6c-956c-7f592db423d9)
![Screenshot_2024-07-07-07-25-11-614_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/c273f5f6-1e51-4c18-bc69-9c9641216b36)
![Screenshot_2024-07-07-07-25-22-958_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/2ea3c79f-dcc0-406a-a88b-2094ecdd6232)
![Screenshot_2024-07-07-07-25-31-204_com eltechs ed](https://github.com/city41/neospriteviewer/assets/102007715/693c6ff7-3d65-4ce0-963a-09ff85acada5)

**Comment by city41** [comment] 2024-07-11 12:59
This is a duplicate of #22

**Closed as completed by city41** 2024-07-11 12:59 UTC
